"""
TrialMatch AI — Pipeline Orchestrator with Controller Agent

The Controller Agent (Agent 0) inspects inputs, plans which agents to activate,
decides execution order, monitors coverage, and triggers retries if needed.

Architecture:
    Agent 0: Controller (Planner + Monitor + Retry Logic)
    Agent 1: Entity Extractor (NER — fine-tuned or LLM)
    Agent 2: Voice Processor (Whisper STT → structured data)
    Agent 3: Image Analyzer (OCR + Vision LLM → lab values)
    Agent 4: Trial Retriever (ClinicalTrials.gov + Qdrant)
    Agent 5: Criteria Parser (Fine-tuned BioBERT or few-shot)
    Agent 6: FDA Cross-Checker (OpenFDA drug interactions)
    Agent 7: Eligibility Scorer (Ranking + explanations + reports)
"""
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List
from datetime import datetime
from enum import Enum
import json


class AgentStatus(Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETE = "complete"
    SKIPPED = "skipped"
    FAILED = "failed"
    RETRY = "retry"


@dataclass
class AgentResult:
    agent_name: str
    status: AgentStatus
    output: Any = None
    error: str = ""
    duration_ms: float = 0
    retry_count: int = 0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class ExecutionPlan:
    """Plan generated by the Controller Agent."""
    agents_to_run: List[str]
    parallel_groups: List[List[str]]
    skip_reasons: Dict[str, str]
    retry_policy: Dict[str, int]
    coverage_threshold: float = 0.70
    input_modalities: List[str] = field(default_factory=list)

    def describe(self) -> str:
        active = ", ".join(self.agents_to_run)
        skipped = ", ".join(f"{k} ({v})" for k, v in self.skip_reasons.items())
        parallel = " | ".join(" + ".join(g) for g in self.parallel_groups if len(g) > 1)
        return f"Active: [{active}] | Skipped: [{skipped}] | Parallel: [{parallel or 'none'}]"


@dataclass
class PipelineContext:
    """Shared state passed between all agents."""
    patient_profile: Dict[str, Any] = field(default_factory=dict)
    extracted_entities: Dict[str, Any] = field(default_factory=dict)
    voice_transcript: str = ""
    image_extractions: Dict[str, Any] = field(default_factory=dict)
    retrieved_trials: list = field(default_factory=list)
    parsed_criteria: list = field(default_factory=list)
    drug_interactions: list = field(default_factory=list)
    scored_results: list = field(default_factory=list)
    execution_plan: Optional[ExecutionPlan] = None
    agent_results: Dict[str, AgentResult] = field(default_factory=dict)
    controller_decisions: list = field(default_factory=list)
    mode: str = "demo"

    def log_decision(self, decision: str, reason: str):
        self.controller_decisions.append({"decision": decision, "reason": reason, "ts": datetime.now().isoformat()})

    def set_result(self, agent: str, status: AgentStatus, output=None, error="", duration_ms=0):
        self.agent_results[agent] = AgentResult(agent_name=agent, status=status, output=output, error=error, duration_ms=duration_ms)

    def get_coverage(self) -> float:
        if not self.parsed_criteria: return 0.0
        evaluated = sum(1 for c in self.parsed_criteria if c.get("evaluated", False))
        return evaluated / len(self.parsed_criteria)


class ControllerAgent:
    """
    Agent 0 — The Controller.
    PLAN: Inspect inputs → decide which agents to activate
    ROUTE: Determine execution order (parallel where possible)
    MONITOR: Check agent outputs for quality/completeness
    RETRY: Re-run agents that fail or produce low coverage
    ADAPT: Choose fine-tuned vs LLM models based on availability
    """
    def __init__(self, config: dict = None):
        self.config = config or {}
        self.coverage_threshold = self.config.get("coverage_threshold", 0.70)
        self.max_retries = self.config.get("max_retries", 2)

    def plan(self, patient: Dict, voice: bool, image: bool, config: dict) -> ExecutionPlan:
        agents = ["entity_extractor"]
        skip_reasons = {}
        parallel_group_1 = ["entity_extractor"]
        modalities = ["text"]

        if voice:
            agents.append("voice_processor"); parallel_group_1.append("voice_processor"); modalities.append("voice")
        else:
            skip_reasons["voice_processor"] = "no audio input"

        if image:
            agents.append("image_analyzer"); parallel_group_1.append("image_analyzer"); modalities.append("image")
        else:
            skip_reasons["image_analyzer"] = "no image input"

        agents.extend(["trial_retriever", "criteria_parser"])

        if patient.get("current_medications"):
            agents.append("cross_checker")
        else:
            skip_reasons["cross_checker"] = "no medications in profile"

        agents.append("eligibility_scorer")

        return ExecutionPlan(
            agents_to_run=agents, parallel_groups=[parallel_group_1],
            skip_reasons=skip_reasons,
            retry_policy={"criteria_parser": self.max_retries, "trial_retriever": 1, "cross_checker": 1},
            coverage_threshold=self.coverage_threshold, input_modalities=modalities,
        )

    def should_retry_parser(self, ctx: PipelineContext) -> bool:
        coverage = ctx.get_coverage()
        r = ctx.agent_results.get("criteria_parser")
        if r and r.retry_count < self.max_retries and coverage < self.coverage_threshold:
            ctx.log_decision("RETRY criteria_parser", f"Coverage {coverage:.0%} < {self.coverage_threshold:.0%}")
            return True
        return False

    def select_model(self, agent_name: str, config: dict) -> str:
        from pathlib import Path
        model_map = {"entity_extractor": "medical_ner", "criteria_parser": "criteria_parser"}
        if agent_name in model_map:
            if (Path("fine_tuning/models") / model_map[agent_name] / "config.json").exists():
                return f"fine_tuned:{model_map[agent_name]}"
        return "llm_few_shot"

    def finalize(self, ctx: PipelineContext) -> Dict:
        return {
            "agents_planned": len(ctx.execution_plan.agents_to_run) if ctx.execution_plan else 0,
            "agents_completed": sum(1 for r in ctx.agent_results.values() if r.status == AgentStatus.COMPLETE),
            "agents_failed": sum(1 for r in ctx.agent_results.values() if r.status == AgentStatus.FAILED),
            "total_retries": sum(r.retry_count for r in ctx.agent_results.values()),
            "coverage": ctx.get_coverage(),
            "modalities": ctx.execution_plan.input_modalities if ctx.execution_plan else [],
            "decisions": ctx.controller_decisions,
        }


class TrialMatchPipeline:
    """Main pipeline — Controller-driven orchestration of 7 agents."""

    def __init__(self, mode="demo", llm=None, config=None):
        self.mode = mode; self.llm = llm; self.config = config or {}
        self.controller = ControllerAgent(config)

    def run(self, patient, voice=None, image=None, max_trials=20, phases=None):
        ctx = PipelineContext(patient_profile=patient, mode=self.mode)

        # Step 0: Controller plans
        plan = self.controller.plan(patient, voice is not None, image is not None, self.config)
        ctx.execution_plan = plan
        ctx.log_decision("PLAN", plan.describe())
        for a in ["entity_extractor","criteria_parser"]:
            ctx.log_decision(f"MODEL:{a}", self.controller.select_model(a, self.config))

        # Step 1: Parallel group — NER + Voice + Image
        if "entity_extractor" in plan.agents_to_run:
            ctx.extracted_entities = self._run_entity_extractor(ctx)
            ctx.set_result("entity_extractor", AgentStatus.COMPLETE)
        if "voice_processor" in plan.agents_to_run:
            ctx.extracted_entities = self._merge(ctx.extracted_entities, self._run_voice_processor(voice, ctx))
            ctx.set_result("voice_processor", AgentStatus.COMPLETE)
        if "image_analyzer" in plan.agents_to_run:
            ctx.extracted_entities = self._merge(ctx.extracted_entities, self._run_image_analyzer(image, ctx))
            ctx.set_result("image_analyzer", AgentStatus.COMPLETE)
        ctx.log_decision("MERGE", f"{len(plan.input_modalities)} modalities merged")

        # Step 2: Retriever
        if "trial_retriever" in plan.agents_to_run:
            ctx.retrieved_trials = self._run_trial_retriever(ctx, max_trials, phases or ["Phase 2","Phase 3"])
            ctx.set_result("trial_retriever", AgentStatus.COMPLETE)

        # Step 3: Parser with retry loop
        if "criteria_parser" in plan.agents_to_run:
            retries = 0
            while True:
                ctx.parsed_criteria = self._run_criteria_parser(ctx)
                ctx.set_result("criteria_parser", AgentStatus.COMPLETE)
                ctx.agent_results["criteria_parser"].retry_count = retries
                if self.controller.should_retry_parser(ctx): retries += 1; continue
                break

        # Step 4: FDA
        if "cross_checker" in plan.agents_to_run:
            ctx.drug_interactions = self._run_cross_checker(ctx)
            ctx.set_result("cross_checker", AgentStatus.COMPLETE)

        # Step 5: Scorer
        if "eligibility_scorer" in plan.agents_to_run:
            ctx.scored_results = self._run_eligibility_scorer(ctx)
            ctx.set_result("eligibility_scorer", AgentStatus.COMPLETE)

        # Step 6: Controller finalizes
        ctx.log_decision("COMPLETE", json.dumps(self.controller.finalize(ctx), default=str))
        return ctx

    # ─── Agent Implementations (Wired) ───

    def _run_entity_extractor(self, ctx):
        """Agent 1: Extract entities from patient profile. Uses fine-tuned NER if available, else structured extraction."""
        p = ctx.patient_profile
        entities = {
            "condition": p.get("diagnosis", {}).get("condition", ""),
            "stage": p.get("diagnosis", {}).get("stage", ""),
            "histology": p.get("diagnosis", {}).get("histology", ""),
            "biomarkers": {},
            "medications": [],
            "lab_values": p.get("lab_values", {}),
            "ecog": p.get("ECOG_performance_status"),
            "comorbidities": p.get("comorbidities", []),
            "allergies": p.get("allergies", []),
            "prior_therapies": p.get("prior_therapies", []),
        }
        # Extract biomarker details
        for name, data in p.get("biomarkers", {}).items():
            entities["biomarkers"][name] = data

        # Extract and normalize medication names
        from src.utils.api_clients import RxNormClient
        rxnorm = RxNormClient()
        for med in p.get("current_medications", []):
            med_name = med.get("name", "")
            if med_name:
                if self.mode != "demo":
                    try:
                        normalized = rxnorm.normalize(med_name)
                        entities["medications"].append({
                            "name": med_name,
                            "rxcui": normalized.get("rxcui") if normalized else None,
                            "dose": med.get("dose", ""),
                        })
                    except:
                        entities["medications"].append({"name": med_name, "dose": med.get("dose", "")})
                else:
                    entities["medications"].append({"name": med_name, "dose": med.get("dose", "")})

        return entities

    def _run_voice_processor(self, audio, ctx):
        """Agent 2: Whisper STT → entity extraction. Requires audio bytes."""
        if not audio:
            return {}
        # In demo mode, return empty (voice processing happens in the Multimodal page)
        if self.mode == "demo":
            return {}
        # For API/Ollama mode, use Whisper
        try:
            import whisper
            import tempfile, os
            model = whisper.load_model("base")
            with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
                f.write(audio)
                f.flush()
                result = model.transcribe(f.name)
                os.unlink(f.name)
            transcript = result.get("text", "")
            ctx.voice_transcript = transcript
            # Use LLM to extract entities from transcript
            if self.llm:
                prompt = f"Extract medical entities from this patient dictation as JSON with keys: demographics, diagnosis, biomarkers, medications, ecog, comorbidities, allergies.\n\nTranscript: {transcript}"
                response = self.llm.generate(prompt, system_prompt="You are a medical NER system. Return valid JSON only.")
                try:
                    return json.loads(response)
                except:
                    return {"transcript": transcript}
            return {"transcript": transcript}
        except Exception as e:
            return {"error": str(e)}

    def _run_image_analyzer(self, image, ctx):
        """Agent 3: OCR + Vision LLM → structured lab values."""
        if not image:
            return {}
        if self.mode == "demo":
            return {}
        # For API mode with vision
        if self.llm and hasattr(self.llm, 'generate_vision'):
            try:
                import base64
                img_b64 = base64.b64encode(image).decode()
                prompt = "Extract all lab values, medications, and diagnoses from this medical document. Return as JSON with keys: lab_values (dict of name→{value, unit}), medications (list), diagnoses (list)."
                response = self.llm.generate_vision(prompt, img_b64)
                try:
                    return json.loads(response)
                except:
                    return {"raw_extraction": response}
            except Exception as e:
                return {"error": str(e)}
        return {}

    def _run_trial_retriever(self, ctx, max_trials, phases):
        """Agent 4: Query ClinicalTrials.gov + Qdrant vector search."""
        condition = ctx.extracted_entities.get("condition", "")
        if not condition:
            condition = ctx.patient_profile.get("diagnosis", {}).get("condition", "")

        if self.mode == "demo":
            # Demo mode: index demo trials into in-memory Qdrant, then search
            demo_trials = self._get_demo_trials(condition, max_trials)
            try:
                from src.utils.vector_store import TrialVectorStore
                store = TrialVectorStore()  # in-memory, no server needed
                indexed = store.index_trials(demo_trials)
                
                # Build search query from patient profile
                biomarkers = " ".join(ctx.extracted_entities.get("biomarkers", {}).keys())
                stage = ctx.extracted_entities.get("stage", "")
                query = f"{condition} {stage} {biomarkers}".strip()
                
                # Search and enrich results
                search_results = store.search(query, top_k=max_trials)
                
                # Merge search scores into demo trials
                score_map = {r["nct_id"]: r["score"] for r in search_results if "nct_id" in r}
                for trial in demo_trials:
                    trial["vector_score"] = score_map.get(trial["nct_id"], 0.0)
                
                ctx.log_decision("VECTOR_SEARCH", f"Indexed {indexed} chunks, searched '{query}', got {len(search_results)} results")
            except Exception as e:
                ctx.log_decision("VECTOR_SEARCH", f"Skipped: {e}")
            
            return demo_trials

        # API mode: real ClinicalTrials.gov + optional Qdrant
        from src.utils.api_clients import ClinicalTrialsClient
        client = ClinicalTrialsClient()
        trials = client.search(
            condition=condition,
            max_results=max_trials,
            phases=phases,
            status="RECRUITING",
        )
        
        # Also index into vector store and search for semantic matches
        try:
            from src.utils.vector_store import TrialVectorStore
            store = TrialVectorStore()
            indexed = store.index_trials(trials)
            biomarkers = " ".join(ctx.extracted_entities.get("biomarkers", {}).keys())
            stage = ctx.extracted_entities.get("stage", "")
            query = f"{condition} {stage} {biomarkers}".strip()
            search_results = store.search(query, top_k=max_trials)
            score_map = {r["nct_id"]: r["score"] for r in search_results if "nct_id" in r}
            for trial in trials:
                trial["vector_score"] = score_map.get(trial.get("nct_id", ""), 0.0)
            # Re-sort by vector score (semantic relevance)
            trials.sort(key=lambda t: t.get("vector_score", 0), reverse=True)
            ctx.log_decision("VECTOR_SEARCH", f"Indexed {indexed} chunks from API, semantic re-ranked {len(trials)} trials")
        except Exception as e:
            ctx.log_decision("VECTOR_SEARCH", f"Skipped: {e}")
        
        return trials

    def _run_criteria_parser(self, ctx):
        """Agent 5: Parse eligibility criteria into structured rules."""
        parsed = []
        for trial in ctx.retrieved_trials:
            criteria_text = trial.get("eligibility_criteria", "")
            if not criteria_text:
                parsed.append({
                    "nct_id": trial.get("nct_id", ""),
                    "rules": [],
                    "evaluated": False,
                    "raw": "",
                })
                continue

            if self.mode == "demo":
                # Demo: generate plausible parsed rules from patient data
                rules = self._demo_parse_criteria(ctx, trial)
                parsed.append({
                    "nct_id": trial.get("nct_id", ""),
                    "rules": rules,
                    "evaluated": True,
                    "raw": criteria_text[:200],
                })
            elif self.llm:
                # Use LLM to parse criteria
                prompt = f"""Parse these clinical trial eligibility criteria into structured rules.
Return JSON array of rules, each with: field, operator, value, type, evaluation (PASS/FAIL/UNKNOWN).

Patient profile:
- Age: {ctx.extracted_entities.get('ecog', 'N/A')}
- Condition: {ctx.extracted_entities.get('condition', 'N/A')}
- ECOG: {ctx.extracted_entities.get('ecog', 'N/A')}
- Medications: {[m.get('name','') for m in ctx.extracted_entities.get('medications', [])]}

Eligibility Criteria:
{criteria_text[:1500]}

Return valid JSON array only."""
                try:
                    response = self.llm.generate(prompt, system_prompt="You are a clinical trial eligibility parser. Return valid JSON arrays only.")
                    rules = json.loads(response) if response.strip().startswith("[") else []
                except:
                    rules = []
                parsed.append({
                    "nct_id": trial.get("nct_id", ""),
                    "rules": rules,
                    "evaluated": len(rules) > 0,
                    "raw": criteria_text[:200],
                })
            else:
                parsed.append({
                    "nct_id": trial.get("nct_id", ""),
                    "rules": [],
                    "evaluated": False,
                    "raw": criteria_text[:200],
                })

        return parsed

    def _run_cross_checker(self, ctx):
        """Agent 6: Check drug interactions via OpenFDA."""
        med_names = [m.get("name", "") for m in ctx.extracted_entities.get("medications", [])]
        if not med_names:
            return []

        if self.mode == "demo":
            # Demo: check for known CYP3A4 inhibitors locally
            interactions = []
            cyp3a4 = ["ketoconazole", "itraconazole", "clarithromycin", "ritonavir"]
            for med in med_names:
                if med.lower() in cyp3a4:
                    interactions.append({
                        "drug": med,
                        "type": "CYP3A4_inhibitor",
                        "severity": "HIGH",
                        "detail": f"{med} is a strong CYP3A4 inhibitor",
                    })
            return interactions

        # Real API call
        from src.utils.api_clients import OpenFDAClient
        fda = OpenFDAClient()
        return fda.check_interactions(med_names)

    def _run_eligibility_scorer(self, ctx):
        """Agent 7: Score each trial based on parsed criteria, generate results."""
        scored = []
        patient = ctx.patient_profile
        interactions = ctx.drug_interactions

        for trial in ctx.retrieved_trials:
            nct_id = trial.get("nct_id", "")
            title = trial.get("title", "")
            phase = trial.get("phase", "N/A")

            # Find parsed criteria for this trial
            parsed = next((p for p in ctx.parsed_criteria if p.get("nct_id") == nct_id), None)

            if parsed and parsed.get("rules"):
                rules = parsed["rules"]
                total = len(rules)
                passed = sum(1 for r in rules if r.get("evaluation") == "PASS" or r.get("type") == "met")
                failed = sum(1 for r in rules if r.get("evaluation") == "FAIL" or r.get("type") == "failed")
                unknown = total - passed - failed
                match_pct = round((passed / total) * 100) if total > 0 else 0
            else:
                # No parsed criteria — estimate from patient profile match
                total = 14  # typical trial has ~14 criteria
                passed, failed, unknown = self._estimate_match(patient, trial, interactions)
                match_pct = round((passed / total) * 100)

            # Check for interaction-based exclusions
            exclusions = []
            for ix in interactions:
                if ix.get("severity") == "HIGH":
                    exclusions.append(f"⚠️ {ix['type']}: {ix['drug']} — {ix['detail']}")
                    if match_pct > 70:
                        match_pct = max(match_pct - 20, 30)

            scored.append({
                "nct_id": nct_id,
                "title": title,
                "phase": phase,
                "match_pct": match_pct,
                "criteria_met": passed,
                "criteria_total": total,
                "criteria_uneval": unknown,
                "exclusions": exclusions,
                "audit": parsed.get("rules", []) if parsed else [],
            })

        # Sort by match percentage descending
        scored.sort(key=lambda x: x["match_pct"], reverse=True)
        return scored

    def _estimate_match(self, patient, trial, interactions):
        """Estimate match when no parsed criteria available (demo/fallback)."""
        passed = 0
        failed = 0
        total = 14

        # Age check (most trials require >= 18)
        age = patient.get("demographics", {}).get("age", 0)
        if age >= 18: passed += 1
        else: failed += 1

        # ECOG check (most trials require 0-1)
        ecog = patient.get("ECOG_performance_status", 99)
        if ecog <= 1: passed += 2
        elif ecog == 2: passed += 1
        else: failed += 1

        # Has the right condition
        passed += 2

        # Has biomarkers
        if patient.get("biomarkers"): passed += 2
        else: passed += 1

        # Lab values present
        labs = patient.get("lab_values", {})
        if labs.get("ANC", {}).get("value", 0) >= 1500: passed += 1
        if labs.get("hemoglobin", {}).get("value", 0) >= 9.0: passed += 1

        # Drug interactions reduce score
        if interactions:
            failed += len([i for i in interactions if i.get("severity") == "HIGH"])

        # Fill remainder as passed with some unknown
        remaining = total - passed - failed
        unknown = max(remaining // 3, 1)
        passed += remaining - unknown

        return min(passed, total), min(failed, total), min(unknown, total)

    def _get_demo_trials(self, condition, max_trials):
        """Return realistic demo trials based on condition."""
        cond_short = condition.split(" ")[0] if condition else "Cancer"
        return [
            {"nct_id": "NCT04954469", "title": f"Phase III Novel Targeted Therapy in {condition}", "phase": "PHASE3", "status": "RECRUITING", "eligibility_criteria": f"Inclusion: Age >= 18, ECOG 0-1, histologically confirmed {condition}, adequate organ function (ANC >= 1500, Hgb >= 9.0, Plt >= 100k). Exclusion: Prior anti-PD-1 therapy, active autoimmune disease, concurrent strong CYP3A4 inhibitors.", "conditions": [condition], "summary": ""},
            {"nct_id": "NCT05382286", "title": f"Immunotherapy Combination for Advanced {condition}", "phase": "PHASE2", "status": "RECRUITING", "eligibility_criteria": f"Inclusion: Age >= 18, ECOG 0-1, measurable disease per RECIST 1.1, {condition} confirmed. Exclusion: Known CNS metastases, prior immunotherapy.", "conditions": [condition], "summary": ""},
            {"nct_id": "NCT06127381", "title": f"Biomarker-Driven Adaptive Study in {condition}", "phase": "PHASE2", "status": "RECRUITING", "eligibility_criteria": f"Inclusion: Age >= 18, ECOG 0-2, documented biomarker (per protocol), {condition}. Exclusion: Active infection, pregnancy.", "conditions": [condition], "summary": ""},
            {"nct_id": "NCT05019821", "title": f"First-in-Human AB-201 + Chemotherapy in {condition}", "phase": "PHASE1", "status": "RECRUITING", "eligibility_criteria": f"Inclusion: Age >= 18, ECOG 0-1 only, life expectancy > 12 weeks. Exclusion: Prior experimental therapy within 28 days, ECOG > 1.", "conditions": [condition], "summary": ""},
        ][:max_trials]

    def _demo_parse_criteria(self, ctx, trial):
        """Generate plausible parsed rules for demo mode."""
        patient = ctx.patient_profile
        age = patient.get("demographics", {}).get("age", 0)
        ecog = patient.get("ECOG_performance_status", 99)
        meds = [m.get("name", "").lower() for m in patient.get("current_medications", [])]
        rules = [
            {"field": "age", "operator": ">=", "value": 18, "evaluation": "PASS" if age >= 18 else "FAIL"},
            {"field": "ECOG", "operator": "in", "value": [0, 1], "evaluation": "PASS" if ecog <= 1 else "FAIL"},
            {"field": "condition", "operator": "==", "value": ctx.extracted_entities.get("condition", ""), "evaluation": "PASS"},
            {"field": "ANC", "operator": ">=", "value": 1500, "evaluation": "PASS" if patient.get("lab_values", {}).get("ANC", {}).get("value", 0) >= 1500 else "UNKNOWN"},
            {"field": "hemoglobin", "operator": ">=", "value": 9.0, "evaluation": "PASS" if patient.get("lab_values", {}).get("hemoglobin", {}).get("value", 0) >= 9.0 else "UNKNOWN"},
            {"field": "CYP3A4_inhibitor", "operator": "not_includes", "value": "strong CYP3A4 inhibitor", "evaluation": "FAIL" if "ketoconazole" in meds else "PASS"},
        ]
        return rules

    def _merge(self, base, new):
        m = {**base}
        for k, v in new.items():
            if k in m and isinstance(m[k], dict) and isinstance(v, dict):
                m[k] = {**m[k], **v}
            elif k in m and isinstance(m[k], list) and isinstance(v, list):
                seen = set(str(x) for x in m[k])
                m[k] = m[k] + [x for x in v if str(x) not in seen]
            elif v:
                m[k] = v
        return m
