"""
TrialMatch AI — Pipeline Orchestrator with Controller Agent

The Controller Agent (Agent 0) inspects inputs, plans which agents to activate,
decides execution order, monitors coverage, and triggers retries if needed.

Architecture:
    Agent 0: Controller (Planner + Monitor + Retry Logic)
    Agent 1: Entity Extractor (NER — fine-tuned or LLM)
    Agent 2: Voice Processor (Whisper STT → structured data)
    Agent 3: Image Analyzer (OCR + Vision LLM → lab values)
    Agent 4: Trial Retriever (ClinicalTrials.gov + Qdrant)
    Agent 5: Criteria Parser (Fine-tuned BioBERT or few-shot)
    Agent 6: FDA Cross-Checker (OpenFDA drug interactions)
    Agent 7: Eligibility Scorer (Ranking + explanations + reports)
"""
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List
from datetime import datetime
from enum import Enum
import json


class AgentStatus(Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETE = "complete"
    SKIPPED = "skipped"
    FAILED = "failed"
    RETRY = "retry"


@dataclass
class AgentResult:
    agent_name: str
    status: AgentStatus
    output: Any = None
    error: str = ""
    duration_ms: float = 0
    retry_count: int = 0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class ExecutionPlan:
    """Plan generated by the Controller Agent."""
    agents_to_run: List[str]
    parallel_groups: List[List[str]]
    skip_reasons: Dict[str, str]
    retry_policy: Dict[str, int]
    coverage_threshold: float = 0.70
    input_modalities: List[str] = field(default_factory=list)

    def describe(self) -> str:
        active = ", ".join(self.agents_to_run)
        skipped = ", ".join(f"{k} ({v})" for k, v in self.skip_reasons.items())
        parallel = " | ".join(" + ".join(g) for g in self.parallel_groups if len(g) > 1)
        return f"Active: [{active}] | Skipped: [{skipped}] | Parallel: [{parallel or 'none'}]"


@dataclass
class PipelineContext:
    """Shared state passed between all agents."""
    patient_profile: Dict[str, Any] = field(default_factory=dict)
    extracted_entities: Dict[str, Any] = field(default_factory=dict)
    voice_transcript: str = ""
    image_extractions: Dict[str, Any] = field(default_factory=dict)
    retrieved_trials: list = field(default_factory=list)
    parsed_criteria: list = field(default_factory=list)
    drug_interactions: list = field(default_factory=list)
    scored_results: list = field(default_factory=list)
    execution_plan: Optional[ExecutionPlan] = None
    agent_results: Dict[str, AgentResult] = field(default_factory=dict)
    controller_decisions: list = field(default_factory=list)
    mode: str = "demo"

    def log_decision(self, decision: str, reason: str):
        self.controller_decisions.append({"decision": decision, "reason": reason, "ts": datetime.now().isoformat()})

    def set_result(self, agent: str, status: AgentStatus, output=None, error="", duration_ms=0):
        self.agent_results[agent] = AgentResult(agent_name=agent, status=status, output=output, error=error, duration_ms=duration_ms)

    def get_coverage(self) -> float:
        if not self.parsed_criteria: return 0.0
        evaluated = sum(1 for c in self.parsed_criteria if c.get("evaluated", False))
        return evaluated / len(self.parsed_criteria)


class ControllerAgent:
    """
    Agent 0 — The Controller.
    PLAN: Inspect inputs → decide which agents to activate
    ROUTE: Determine execution order (parallel where possible)
    MONITOR: Check agent outputs for quality/completeness
    RETRY: Re-run agents that fail or produce low coverage
    ADAPT: Choose fine-tuned vs LLM models based on availability
    """
    def __init__(self, config: dict = None):
        self.config = config or {}
        self.coverage_threshold = self.config.get("coverage_threshold", 0.70)
        self.max_retries = self.config.get("max_retries", 2)

    def plan(self, patient: Dict, voice: bool, image: bool, config: dict) -> ExecutionPlan:
        agents = ["entity_extractor"]
        skip_reasons = {}
        parallel_group_1 = ["entity_extractor"]
        modalities = ["text"]

        if voice:
            agents.append("voice_processor"); parallel_group_1.append("voice_processor"); modalities.append("voice")
        else:
            skip_reasons["voice_processor"] = "no audio input"

        if image:
            agents.append("image_analyzer"); parallel_group_1.append("image_analyzer"); modalities.append("image")
        else:
            skip_reasons["image_analyzer"] = "no image input"

        agents.extend(["trial_retriever", "criteria_parser"])

        if patient.get("current_medications"):
            agents.append("cross_checker")
        else:
            skip_reasons["cross_checker"] = "no medications in profile"

        agents.append("eligibility_scorer")

        return ExecutionPlan(
            agents_to_run=agents, parallel_groups=[parallel_group_1],
            skip_reasons=skip_reasons,
            retry_policy={"criteria_parser": self.max_retries, "trial_retriever": 1, "cross_checker": 1},
            coverage_threshold=self.coverage_threshold, input_modalities=modalities,
        )

    def should_retry_parser(self, ctx: PipelineContext) -> bool:
        coverage = ctx.get_coverage()
        r = ctx.agent_results.get("criteria_parser")
        if r and r.retry_count < self.max_retries and coverage < self.coverage_threshold:
            ctx.log_decision("RETRY criteria_parser", f"Coverage {coverage:.0%} < {self.coverage_threshold:.0%}")
            return True
        return False

    def select_model(self, agent_name: str, config: dict) -> str:
        from pathlib import Path
        model_map = {"entity_extractor": "medical_ner", "criteria_parser": "criteria_parser"}
        if agent_name in model_map:
            if (Path("fine_tuning/models") / model_map[agent_name] / "config.json").exists():
                return f"fine_tuned:{model_map[agent_name]}"
        return "llm_few_shot"

    def finalize(self, ctx: PipelineContext) -> Dict:
        return {
            "agents_planned": len(ctx.execution_plan.agents_to_run) if ctx.execution_plan else 0,
            "agents_completed": sum(1 for r in ctx.agent_results.values() if r.status == AgentStatus.COMPLETE),
            "agents_failed": sum(1 for r in ctx.agent_results.values() if r.status == AgentStatus.FAILED),
            "total_retries": sum(r.retry_count for r in ctx.agent_results.values()),
            "coverage": ctx.get_coverage(),
            "modalities": ctx.execution_plan.input_modalities if ctx.execution_plan else [],
            "decisions": ctx.controller_decisions,
        }


class TrialMatchPipeline:
    """Main pipeline — Controller-driven orchestration of 7 agents."""

    def __init__(self, mode="demo", llm=None, config=None):
        self.mode = mode; self.llm = llm; self.config = config or {}
        self.controller = ControllerAgent(config)

    def run(self, patient, voice=None, image=None, max_trials=20, phases=None):
        ctx = PipelineContext(patient_profile=patient, mode=self.mode)

        # Step 0: Controller plans
        plan = self.controller.plan(patient, voice is not None, image is not None, self.config)
        ctx.execution_plan = plan
        ctx.log_decision("PLAN", plan.describe())
        for a in ["entity_extractor","criteria_parser"]:
            ctx.log_decision(f"MODEL:{a}", self.controller.select_model(a, self.config))

        # Step 1: Parallel group — NER + Voice + Image
        if "entity_extractor" in plan.agents_to_run:
            ctx.extracted_entities = self._run_entity_extractor(ctx)
            ctx.set_result("entity_extractor", AgentStatus.COMPLETE)
        if "voice_processor" in plan.agents_to_run:
            ctx.extracted_entities = self._merge(ctx.extracted_entities, self._run_voice_processor(voice, ctx))
            ctx.set_result("voice_processor", AgentStatus.COMPLETE)
        if "image_analyzer" in plan.agents_to_run:
            ctx.extracted_entities = self._merge(ctx.extracted_entities, self._run_image_analyzer(image, ctx))
            ctx.set_result("image_analyzer", AgentStatus.COMPLETE)
        ctx.log_decision("MERGE", f"{len(plan.input_modalities)} modalities merged")

        # Step 2: Retriever
        if "trial_retriever" in plan.agents_to_run:
            ctx.retrieved_trials = self._run_trial_retriever(ctx, max_trials, phases or ["Phase 2","Phase 3"])
            ctx.set_result("trial_retriever", AgentStatus.COMPLETE)

        # Step 3: Parser with retry loop
        if "criteria_parser" in plan.agents_to_run:
            retries = 0
            while True:
                ctx.parsed_criteria = self._run_criteria_parser(ctx)
                ctx.set_result("criteria_parser", AgentStatus.COMPLETE)
                ctx.agent_results["criteria_parser"].retry_count = retries
                if self.controller.should_retry_parser(ctx): retries += 1; continue
                break

        # Step 4: FDA
        if "cross_checker" in plan.agents_to_run:
            ctx.drug_interactions = self._run_cross_checker(ctx)
            ctx.set_result("cross_checker", AgentStatus.COMPLETE)

        # Step 5: Scorer
        if "eligibility_scorer" in plan.agents_to_run:
            ctx.scored_results = self._run_eligibility_scorer(ctx)
            ctx.set_result("eligibility_scorer", AgentStatus.COMPLETE)

        # Step 6: Controller finalizes
        ctx.log_decision("COMPLETE", json.dumps(self.controller.finalize(ctx), default=str))
        return ctx

    # ─── Agent stubs ───
    def _run_entity_extractor(self, ctx): 
        p = ctx.patient_profile
        return {"condition":p.get("diagnosis",{}).get("condition",""),"stage":p.get("diagnosis",{}).get("stage",""),"biomarkers":list(p.get("biomarkers",{}).keys()),"medications":[m.get("name","") for m in p.get("current_medications",[])],"ecog":p.get("ECOG_performance_status")}
    def _run_voice_processor(self, audio, ctx): return {}
    def _run_image_analyzer(self, image, ctx): return {}
    def _run_trial_retriever(self, ctx, max_trials, phases): return []
    def _run_criteria_parser(self, ctx): return []
    def _run_cross_checker(self, ctx): return []
    def _run_eligibility_scorer(self, ctx): return []
    def _merge(self, base, new):
        m = {**base}
        for k,v in new.items():
            if k in m and isinstance(m[k],dict) and isinstance(v,dict): m[k]={**m[k],**v}
            elif k in m and isinstance(m[k],list) and isinstance(v,list): m[k]=list({str(x):x for x in m[k]+v}.values())
            elif v: m[k]=v
        return m
